import type { Metadata } from "next";
import Link from "next/link";

export const metadata:Metadata={
  title:"Eventbot Dashboard Starter Kit",
  description:"Download the Eventbot dashboard build prompt and populated demonstration workbook.",
};

const tables=["Clients","Venues","Events & calendar","Vendor master","Vendor pricing","Vendor schedules","Budget lines","Budget summary","Teams & members","Assignments","RFQs","Quote comparison","Reputation","Market intelligence","Ticket pricing","Sponsors","Wedding events"];

export default function PromptResourcesPage(){
  return <main className="kit-page">
    <header className="kit-nav"><Link href="/" className="kit-brand">Event<em>bot</em><span>Starter kit</span></Link><a href="#downloads" className="kit-nav-link">Download files ↓</a></header>
    <section className="kit-hero"><div className="kit-hero-copy"><div className="kit-eyebrow">CEO DASHBOARD · BUILD KIT</div><h1>Turn your agency data into an executive dashboard.</h1><p>Two files. One clear workflow. Give the prompt and workbook to an AI coding assistant to generate a responsive HTML dashboard for leadership and daily operations.</p><a className="kit-primary" href="#downloads">Get the starter kit</a></div><div className="kit-hero-visual"><div className="kit-window"><div className="kit-window-bar"><i/><i/><i/><span>EXECUTIVE OVERVIEW</span></div><div className="kit-kpis"><div><span>Booked revenue</span><b>₹3.36 Cr</b><small>▲ Demonstration data</small></div><div><span>Active events</span><b>16</b><small>Across the pipeline</small></div><div><span>Reputation</span><b>4.76</b><small>Composite score</small></div></div><div className="kit-chart"><div><i style={{height:"48%"}}/><em style={{height:"62%"}}/></div><div><i style={{height:"72%"}}/><em style={{height:"85%"}}/></div><div><i style={{height:"54%"}}/><em style={{height:"68%"}}/></div><div><i style={{height:"82%"}}/><em style={{height:"93%"}}/></div><div><i style={{height:"64%"}}/><em style={{height:"76%"}}/></div></div></div></div></section>

    <section className="kit-how"><div className="kit-eyebrow">HOW IT WORKS</div><h2>From download to working dashboard.</h2><div className="kit-steps"><article><span>01</span><h3>Download both files</h3><p>The Markdown file explains the product, UX and analytics. The workbook supplies realistic demonstration data.</p></article><article><span>02</span><h3>Upload them together</h3><p>Attach both files to your preferred AI coding assistant and paste the instruction shown below.</p></article><article><span>03</span><h3>Generate the HTML</h3><p>Ask for a self-contained, responsive dashboard that works on laptop, tablet and mobile.</p></article><article><span>04</span><h3>Review and customise</h3><p>Replace mock records with agency data, adjust branding and verify every chart before business use.</p></article></div></section>

    <section className="kit-downloads" id="downloads"><div className="kit-download-intro"><div className="kit-eyebrow">DOWNLOADS</div><h2>Everything needed to create the preview.</h2><p>Download the prompt plus one data format. The Excel workbook is recommended for Claude; the CSV bundle provides the same tables as separate files.</p></div><div className="kit-file-grid"><article><div className="kit-file-top"><span className="kit-file-icon">MD</span><span>13 KB · Markdown</span></div><h3>Dashboard build prompt</h3><p>Complete instructions covering pages, KPIs, infographics, design system, responsiveness, accessibility and expected HTML output.</p><ul><li>CEO and Operations views</li><li>10 dashboard modules</li><li>Charts and decision signals</li><li>Responsive design rules</li></ul><a href="/api/resources/prompt" download>Download prompt <span>↓</span></a></article><article className="featured"><div className="kit-file-top"><span className="kit-file-icon">XLSX</span><span>42 KB · Excel workbook</span></div><h3>Populated mock data</h3><p>A multi-sheet demonstration workbook with connected events, vendors, budgets, teams, RFQs and commercial intelligence.</p><ul><li>19 connected data tables</li><li>Indian currency and dates</li><li>Events, weddings and schedules</li><li>No private client information</li></ul><a href="/api/resources/data" download>Download Excel data <span>↓</span></a></article><article><div className="kit-file-top"><span className="kit-file-icon">CSV</span><span>18 KB · ZIP archive</span></div><h3>Individual CSV tables</h3><p>The same mock dataset supplied as separate CSV files for tools that prefer plain-text tabular imports.</p><ul><li>19 named CSV tables</li><li>Matching relationship keys</li><li>Easy to inspect and replace</li><li>Optional alternative to Excel</li></ul><a href="/api/resources/csv" download>Download CSV bundle <span>↓</span></a></article></div></section>

    <section className="kit-paste"><div><div className="kit-eyebrow">PASTE THIS WITH THE FILES</div><h2>A simple instruction to begin.</h2></div><div className="kit-code"><span>BUILD INSTRUCTION</span><p>“Use the attached Markdown specification and Excel workbook to build a polished, self-contained executive operations dashboard in HTML, CSS and JavaScript. Load the workbook data into every relevant view, implement all charts and filters, and make the interface responsive for desktop, tablet and mobile. Follow the supplied design system exactly. Return a complete working project and explain how to open it locally.”</p></div></section>

    <section className="kit-data"><div><div className="kit-eyebrow">WHAT IS INSIDE</div><h2>One workbook.<br/>The whole agency.</h2><p>Connected data allows the generated dashboard to tell a coherent story instead of showing isolated sample charts.</p></div><div className="kit-tags">{tables.map((table,index)=><span key={table}><b>{String(index+1).padStart(2,"0")}</b>{table}</span>)}</div></section>

    <section className="kit-note"><div><span>Important</span><h2>Use the mock workbook for demonstrations—not business decisions.</h2></div><p>Before operational use, replace demonstration rows with validated agency data, review financial calculations and protect confidential client information. API keys and passwords should never be placed inside the workbook, prompt or generated HTML.</p></section>
    <footer className="kit-footer"><div className="kit-brand">Event<em>bot</em></div><p>Executive intelligence and operational control for event-management agencies.</p><a href="#downloads">Download starter kit ↑</a></footer>
  </main>;
}
