const state={tables:window.EMBEDDED_TABLES||{},page:"overview",view:localStorage.getItem("dashboard-view")||"ceo",month:new Date(new Date().getFullYear(),new Date().getMonth(),1),query:""};
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const pageFiles={events:"03_events_calendar.csv",vendors:"04_vendor_master.csv",budgets:"07_budget_lines.csv",rfqs:"11_rfqs.csv",teams:"09_teams_members.csv",reputation:"15_reputation_reviews.csv",market:"16_market_intelligence.csv",weddings:"19_wedding_events.csv"};
const pageMeta={events:["PROGRAMME","Events","Pipeline, dates, venues and attendance"],vendors:["PROCUREMENT","Vendors","Directory, reliability and contacts"],budgets:["FINANCE","Budgets","Planned, actual and variance by category"],rfqs:["PROCUREMENT","RFQs","Requests, ceilings and award progress"],teams:["PEOPLE","Teams","Skills, utilization and operating capacity"],reputation:["ADVOCACY","Reputation","Reviews, ratings and NPS"],market:["COMPETITIVE ANALYSIS","Market Intelligence","Competitors, partners and opportunities"],weddings:["EVENT TYPE","Weddings","Wedding programme, budget and readiness"]};
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(n)||0);const num=n=>new Intl.NumberFormat("en-IN").format(Number(n)||0);

function parseCSV(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],next=text[i+1];if(c==='"'&&quoted&&next==='"'){cell+='"';i++;}else if(c==='"'){quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell="";}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&next==='\n')i++;row.push(cell);if(row.some(v=>v!==""))rows.push(row);row=[];cell="";}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row)}if(rows.length<1)return[];const headers=rows[0].map(h=>h.trim());return rows.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??""])))}
async function loadFiles(files){for(const file of files){state.tables[file.name]=parseCSV(await file.text())}updateAll();toast(`${files.length} CSV file${files.length===1?"":"s"} loaded`)}
function table(name){return state.tables[name]||[]}
function updateAll(){const events=table("03_events_calendar.csv"),vendors=table("04_vendor_master.csv"),rfqs=table("11_rfqs.csv"),teams=table("09_teams_members.csv"),reviews=table("15_reputation_reviews.csv"),budgets=table("07_budget_lines.csv");
  $("#file-count").textContent=window.STANDALONE?"Embedded demo data":`${Object.keys(state.tables).length} files loaded`;$("#empty-banner").hidden=Object.values(state.tables).some(r=>r.length);$("#nav-events").textContent=events.length;$("#nav-vendors").textContent=vendors.length;$("#nav-rfqs").textContent=rfqs.length;$("#nav-teams").textContent=new Set(teams.map(r=>r.team_id)).size;const live=events.find(e=>e.status==="live");$("#run-status").textContent=live?`${live.event_name} · ${num(live.confirmed_attendees)} in room`:`${events.length} events available`;
  $("#kpi-revenue").textContent=money(events.reduce((a,e)=>a+(+e.booked_revenue_inr||0),0));$("#kpi-events").textContent=events.filter(e=>!["completed","cancelled"].includes(e.status)).length;$("#kpi-events-note").textContent=events.length?`${events.length} total events loaded`:"No programme loaded";
  const planned=budgets.reduce((a,b)=>a+(+b.planned_inr||0),0),actual=budgets.reduce((a,b)=>a+(+b.actual_inr||0),0);$("#kpi-budget").textContent=planned?`${Math.round(actual/planned*100)}%`:"0%";const avg=reviews.length?reviews.reduce((a,r)=>a+(+r.score||0),0)/reviews.length:0;$("#kpi-reputation").textContent=avg?`${avg.toFixed(2)} / 5`:"—";
  updateRevenue(events);updateTypes(events);updateUpcoming(events);updateAlerts(budgets,teams,rfqs,vendors);applyView(state.view);renderCalendar();if(!["overview","calendar"].includes(state.page))renderDataPage(state.page);
}
function applyView(view){state.view=view;const events=table("03_events_calendar.csv"),budgets=table("07_budget_lines.csv"),teams=table("09_teams_members.csv"),reviews=table("15_reputation_reviews.csv"),now=new Date(),weekEnd=new Date(now.getTime()+7*864e5),inWeek=events.filter(e=>{const d=new Date(e.starts_on);return d>=new Date(now.toDateString())&&d<=weekEnd}).length,live=events.filter(e=>e.status==="live").length,alerts=budgets.filter(b=>(+b.used_pct||0)>=90).length,avgUtil=teams.length?Math.round(teams.reduce((a,m)=>a+(+m.utilization_pct||0),0)/teams.length):0;
  $$('.view-toggle button').forEach(b=>b.classList.toggle("active",b.dataset.view===view));
  if(view==="manager"){$("#overview-eyebrow").textContent="MANAGER RUN OF SHOW";$("#overview-title").textContent="How today is running";$("#overview-subtitle").textContent="Live programme, upcoming load-ins, team capacity and issues requiring action.";$("#kpi-label-1").textContent="Live Right Now";$("#kpi-revenue").textContent=live;$("#kpi-note-1").textContent=live?"Events currently in operation":"No live event at this moment";$("#kpi-label-2").textContent="This Week · Load-ins";$("#kpi-events").textContent=inWeek;$("#kpi-events-note").textContent="Next seven operating days";$("#kpi-label-3").textContent="Budget Alerts";$("#kpi-budget").textContent=alerts;$("#kpi-note-3").textContent="Categories at or above 90%";$("#kpi-label-4").textContent="Team Utilization";$("#kpi-reputation").textContent=`${avgUtil}%`;$("#kpi-note-4").textContent=`${teams.length} people in the roster`;$("#chart-eyebrow").textContent="PRODUCTION VALUE";$("#chart-title").textContent="Booked vs projected event value"}
  else{const booked=events.reduce((a,e)=>a+(+e.booked_revenue_inr||0),0),active=events.filter(e=>!["completed","cancelled"].includes(e.status)).length,planned=budgets.reduce((a,b)=>a+(+b.planned_inr||0),0),actual=budgets.reduce((a,b)=>a+(+b.actual_inr||0),0),rating=reviews.length?reviews.reduce((a,r)=>a+(+r.score||0),0)/reviews.length:0;$("#overview-eyebrow").textContent="EXECUTIVE OVERVIEW";$("#overview-title").textContent="How the business is running";$("#overview-subtitle").textContent="Revenue, programme, people and market signals in one operating view.";$("#kpi-label-1").textContent="Booked Revenue";$("#kpi-revenue").textContent=money(booked);$("#kpi-note-1").textContent="From events calendar";$("#kpi-label-2").textContent="Active Events";$("#kpi-events").textContent=active;$("#kpi-events-note").textContent=`${events.length} total events loaded`;$("#kpi-label-3").textContent="Budget Utilized";$("#kpi-budget").textContent=planned?`${Math.round(actual/planned*100)}%`:"0%";$("#kpi-note-3").textContent="Actual versus planned";$("#kpi-label-4").textContent="Reputation";$("#kpi-reputation").textContent=rating?`${rating.toFixed(2)} / 5`:"—";$("#kpi-note-4").textContent="Composite review score";$("#chart-eyebrow").textContent="FINANCIAL RUN RATE";$("#chart-title").textContent="Actual vs projected revenue"}}
function updateRevenue(events){const chart=$("#revenue-chart");if(!events.length){chart.innerHTML='<div class="chart-empty">Revenue bars will appear after events data is loaded.</div>';return}const grouped={};events.forEach(e=>{const m=(e.starts_on||"Unknown").slice(0,7);grouped[m]??={actual:0,projected:0};grouped[m].actual+=+e.booked_revenue_inr||0;grouped[m].projected+=+e.projected_revenue_inr||0});const entries=Object.entries(grouped).sort().slice(-8),max=Math.max(1,...entries.flatMap(([,v])=>[v.actual,v.projected]));chart.innerHTML=entries.map(([m,v])=>`<div class="bar-group" title="${m}: ${money(v.actual)} booked / ${money(v.projected)} projected"><i class="bar" style="height:${v.actual/max*90}%"></i><i class="bar projected" style="height:${v.projected/max*90}%"></i><label>${m.slice(5)}</label></div>`).join("")}
function updateTypes(events){const counts={};events.forEach(e=>counts[e.event_type||"unknown"]=(counts[e.event_type||"unknown"]||0)+1);const colors=["#ba0013","#1e40af","#0f766e","#b45309","#7c3aed","#64748b"],entries=Object.entries(counts),total=events.length;let pos=0,stops=[];entries.forEach(([_,v],i)=>{const end=pos+v/Math.max(1,total)*100;stops.push(`${colors[i%colors.length]} ${pos}% ${end}%`);pos=end});$("#event-donut").style.background=entries.length?`conic-gradient(${stops.join(",")})`:"var(--border)";$("#event-donut").innerHTML=`<span><b>${total}</b>Total</span>`;$("#type-legend").innerHTML=entries.length?entries.map(([k,v],i)=>`<div><i style="background:${colors[i%colors.length]}"></i><span>${escapeHTML(k.replaceAll("_"," "))}</span><b>${v}</b></div>`).join(""):"<p>No event types loaded</p>"}
function updateUpcoming(events){const rows=events.filter(e=>e.starts_on).sort((a,b)=>a.starts_on.localeCompare(b.starts_on)).slice(0,6);$("#upcoming-body").innerHTML=rows.length?rows.map(e=>`<tr><td>${escapeHTML(e.starts_on)}</td><td><b>${escapeHTML(e.event_name)}</b><br><small>${escapeHTML(e.venue||"Venue TBD")}</small></td><td>${escapeHTML(e.status)}</td><td class="number">${money(e.total_budget_inr)}</td></tr>`).join(""):'<tr><td colspan="4" class="empty-cell">Load `03_events_calendar.csv` to see upcoming events.</td></tr>'}
function updateAlerts(budgets,teams,rfqs,vendors){const alerts=[];budgets.filter(b=>(+b.used_pct||0)>=90).forEach(b=>alerts.push(`${b.event_name}: ${b.budget_category} is ${b.used_pct}% used`));teams.filter(m=>(+m.utilization_pct||0)>90).forEach(m=>alerts.push(`${m.member_name} is at ${m.utilization_pct}% utilization`));rfqs.filter(r=>["sent","collecting"].includes(r.status)).forEach(r=>alerts.push(`${r.rfq_code}: vendor responses are still open`));vendors.filter(v=>(+v.reliability_pct||100)<90).forEach(v=>alerts.push(`${v.vendor_name}: reliability is ${v.reliability_pct}%`));$("#alert-count").textContent=alerts.length;$("#alerts-list").innerHTML=alerts.length?alerts.slice(0,7).map(a=>`<div class="alert-card">${escapeHTML(a)}</div>`).join(""):'<div class="empty-card">No alerts can be calculated without data.</div>'}
function renderCalendar(){const d=state.month,y=d.getFullYear(),m=d.getMonth(),events=table("03_events_calendar.csv");$("#calendar-title").textContent=d.toLocaleDateString("en-IN",{month:"long",year:"numeric"});const start=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),cells=[];for(let i=0;i<start;i++)cells.push({day:new Date(y,m,1-start+i).getDate(),other:true,date:""});for(let day=1;day<=days;day++)cells.push({day,other:false,date:`${y}-${String(m+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`});while(cells.length%7)cells.push({day:cells.length-start-days+1,other:true,date:""});const today=new Date().toISOString().slice(0,10);$("#calendar-grid").innerHTML=cells.map(c=>{const ev=c.date?events.filter(e=>e.starts_on<=c.date&&e.ends_on>=c.date):[];return`<div class="cal-day ${c.other?"other":""} ${c.date===today?"today":""}"><span>${c.day}</span>${ev.map(e=>`<b class="cal-event ${escapeHTML(e.status)}" title="${escapeHTML(e.event_name)}">${escapeHTML((e.starts_at_ist||"").slice(-5))} ${escapeHTML(e.event_name)}</b>`).join("")}</div>`}).join("")}
function renderDataPage(page){const meta=pageMeta[page]||pageMeta.events,filename=pageFiles[page],rows=table(filename),query=$("#table-search").value.toLowerCase(),filtered=query?rows.filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(query))):rows;$("#data-eyebrow").textContent=meta[0];$("#data-title").textContent=meta[1];$("#data-subtitle").textContent=meta[2];$("#table-title").textContent=filename;$("#record-count").textContent=filtered.length;const heads=rows[0]?Object.keys(rows[0]):[];$("#data-table thead").innerHTML=heads.length?`<tr>${heads.map(h=>`<th>${escapeHTML(h.replaceAll("_"," "))}</th>`).join("")}</tr>`:"";$("#data-table tbody").innerHTML=filtered.length?filtered.slice(0,100).map(r=>`<tr>${heads.map(h=>`<td>${h.endsWith("_inr")?money(r[h]):escapeHTML(r[h]||"—")}</td>`).join("")}</tr>`):'<tr><td class="empty-cell">Load the matching CSV template to display this section.</td></tr>';$("#summary-strip").innerHTML=`<div><span>RECORDS</span><b>${num(rows.length)}</b></div><div><span>VISIBLE</span><b>${num(filtered.length)}</b></div><div><span>DATA SOURCE</span><b>${state.tables[filename]?"Loaded":"Empty"}</b></div>`}
function navigate(page){state.page=page;$$('.sidebar a').forEach(a=>a.classList.toggle("active",a.dataset.page===page));$$('.page').forEach(p=>p.classList.remove("active"));if(page==="overview")$("#page-overview").classList.add("active");else if(page==="calendar"){$("#page-calendar").classList.add("active");renderCalendar()}else{$("#page-data").classList.add("active");renderDataPage(page)}$("#sidebar").classList.remove("open");$("#menu-button").setAttribute("aria-expanded","false");location.hash=page}
function exportView(){const filename=pageFiles[state.page];if(!filename||!state.tables[filename])return toast("Load this section's CSV before exporting");const rows=state.tables[filename],heads=Object.keys(rows[0]||{}),csv=[heads,...rows.map(r=>heads.map(h=>r[h]))].map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`filtered_${filename}`;a.click();URL.revokeObjectURL(a.href)}
function escapeHTML(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2400)}
$$('[type=file]').forEach(i=>i.addEventListener("change",e=>loadFiles([...e.target.files])));$$('[data-page]').forEach(a=>a.addEventListener("click",e=>{e.preventDefault();navigate(a.dataset.page)}));$$('[data-go]').forEach(b=>b.addEventListener("click",()=>navigate(b.dataset.go)));$("#menu-button").onclick=()=>{const open=$("#sidebar").classList.toggle("open");$("#menu-button").setAttribute("aria-expanded",String(open))};$("#sidebar-scrim").onclick=()=>$("#sidebar").classList.remove("open");$("#theme-button").onclick=()=>{const next=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=next;localStorage.setItem("theme",next)};$$('.view-toggle button').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;localStorage.setItem("dashboard-view",state.view);applyView(state.view);toast(`${b.textContent} view active`)});$("#table-search").oninput=()=>renderDataPage(state.page);$("#export-button").onclick=exportView;$("#refresh-button").onclick=()=>{updateAll();toast("Dashboard refreshed")};$("#prev-month").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};$("#next-month").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};$("#today-button").onclick=()=>{state.month=new Date(new Date().getFullYear(),new Date().getMonth(),1);renderCalendar()};$("#global-search").addEventListener("keydown",e=>{if(e.key==="Enter"){const q=e.target.value.trim();if(q){navigate("events");$("#table-search").value=q;renderDataPage("events")}}});
document.documentElement.dataset.theme=localStorage.getItem("theme")||"light";setInterval(()=>{const d=new Date();$("#run-date").textContent=d.toLocaleDateString("en-IN",{weekday:"short",day:"2-digit",month:"short",year:"numeric"}).toUpperCase();$("#run-time").textContent=d.toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",hour12:false})+" IST"},1000);navigate(location.hash.slice(1)||"overview");updateAll();
