"use client";

import { useEffect, useMemo, useState } from "react";

type CaseStudy = { id:number; name:string; type:string; client:string; venue:string; city:string; attendees:number; valueInr:number; rating:number|null; highlight:string };
type RateItem = { id:number; name:string; category:string; vendor:string; unit:string; rateInr:number };
type Line = { name:string; quantity:number; unit:string; rate:number };
type Proposal = {
  id:string; status:"Draft"|"Ready"|"Sent"; createdAt:string; client:string; company:string; title:string; eventType:string;
  city:string; date:string; attendees:number; budget:number; objective:string; concept:string; scope:string[]; lines:Line[];
  proofIds:number[]; nextSteps:string;
};

const STORAGE_KEY = "eventbot.proposals.v1";
const sampleBrief = "Hi, we are planning the Apex Motors Annual Dealer Meet in Chennai for 400 dealers and spouses from Tamil Nadu and Kerala. We need venue, stage, food, entertainment and an awards segment. The event should feel energetic and premium. Budget is ₹25–30 lakh, planned for the first week of December. Please send a proposal by Monday. — Ramesh Kumar, Apex Motors";
const money = (value:number) => new Intl.NumberFormat("en-IN", { style:"currency", currency:"INR", maximumFractionDigits:0 }).format(value || 0);

function localDraft(brief:string, cases:CaseStudy[], rates:RateItem[]):Proposal {
  const amount = brief.match(/(?:₹|rs\.?|inr)\s*(\d+(?:\.\d+)?)\s*(lakh|lac|crore)?/i) || brief.match(/(\d+(?:\.\d+)?)\s*(lakh|lac|crore)/i);
  const pax = brief.match(/(\d{2,5})\s*(?:people|persons|pax|dealers|guests)/i);
  const budget = amount ? Number(amount[1]) * (/crore/i.test(amount[2]||"") ? 10_000_000 : /lakh|lac/i.test(amount[2]||"") ? 100_000 : 1) : 2_500_000;
  const attendees = pax ? Number(pax[1]) : 400;
  const type = /wedding/i.test(brief) ? "Wedding" : /launch/i.test(brief) ? "Product launch" : /conference|summit/i.test(brief) ? "Conference" : "Corporate event";
  const signature = brief.match(/[—–]\s*([^,\n]+),\s*([^\n]+?)\s*$/);
  const company = signature?.[2]?.trim() || brief.match(/([A-Z][A-Za-z&]+(?:\s+[A-Z][A-Za-z&]+){1,3})\s+(?:Annual|Dealer|Leadership|Product)/)?.[1] || "Prospective client";
  const client = signature?.[1]?.trim() || "Decision maker";
  const city = brief.match(/(?:in|at)\s+(Chennai|Bengaluru|Bangalore|Mumbai|Delhi|Hyderabad|Pune|Goa|Gurugram)/i)?.[1] || "City to confirm";
  const preferred = rates.slice(0, 8);
  const rawLines:Line[] = preferred.map((r, i) => ({ name:r.name, quantity:i===0 ? 1 : 1, unit:r.unit, rate:r.rateInr }));
  const total = rawLines.reduce((sum, line) => sum + line.quantity * line.rate, 0);
  if (total < budget * .55) rawLines.push({ name:`Guest experience & hospitality (${attendees} guests)`, quantity:attendees, unit:"per guest", rate:Math.max(500, Math.round((budget*.6-total)/attendees)) });
  return { id:crypto.randomUUID(), status:"Draft", createdAt:new Date().toISOString(), client, company, title:`${company} — ${type}`, eventType:type, city, date:"First week of December", attendees, budget, objective:"Create a high-energy, premium experience that strengthens relationships and makes recognition feel meaningful.", concept:"Momentum — a cinematic event journey that moves guests from welcome and connection into celebration, recognition and a memorable shared finale.", scope:["Strategy, concept and experience design","Venue, guest journey and hospitality planning","Stage, sound, lighting and show production","Entertainment, awards and content direction","Vendor coordination, rehearsals and on-ground delivery"], lines:rawLines, proofIds:cases.slice(0,3).map(c=>c.id), nextSteps:"Approve the creative direction and working budget. Eventbot will then lock the venue shortlist, production plan and vendor holds, followed by a detailed project schedule and commercial agreement." };
}

export function ProposalFactory({ caseStudies, rateItems }:{ caseStudies:CaseStudy[]; rateItems:RateItem[] }) {
  const [tab,setTab]=useState<"proposals"|"ratecard"|"proof">("proposals");
  const [mode,setMode]=useState<"list"|"brief"|"document">("list");
  const [brief,setBrief]=useState(""); const [proposal,setProposal]=useState<Proposal|null>(null);
  const [records,setRecords]=useState<Proposal[]>([]); const [generating,setGenerating]=useState(false); const [notice,setNotice]=useState("");
  useEffect(()=>{ try { setRecords(JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")); } catch { setRecords([]); } },[]);
  const save=(next:Proposal)=>{ const updated=[next,...records.filter(r=>r.id!==next.id)]; setProposal(next); setRecords(updated); localStorage.setItem(STORAGE_KEY,JSON.stringify(updated)); setNotice("Saved"); setTimeout(()=>setNotice(""),1400); };
  const total=useMemo(()=>proposal?.lines.reduce((s,l)=>s+l.quantity*l.rate,0)||0,[proposal]);
  async function generate(){ setGenerating(true); let draft=localDraft(brief,caseStudies,rateItems); try { const response=await fetch("/api/proposals/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brief,caseStudies:caseStudies.slice(0,6),rateItems:rateItems.slice(0,30)})}); if(response.ok) draft={...draft,...await response.json(),id:draft.id,createdAt:draft.createdAt,status:"Draft"}; else setNotice("Smart local draft created · connect OpenAI for enhanced copy"); } catch { setNotice("Smart local draft created · AI unavailable"); } save(draft); setMode("document"); setGenerating(false); }
  const patch=(field:keyof Proposal,value:Proposal[keyof Proposal])=>proposal&&save({...proposal,[field]:value});
  const selectedCases=caseStudies.filter(c=>proposal?.proofIds.includes(c.id));
  const proofGuests=selectedCases.reduce((sum,item)=>sum+item.attendees,0);
  const proofValue=selectedCases.reduce((sum,item)=>sum+item.valueInr,0);
  const ratedCases=selectedCases.filter(item=>item.rating!==null);
  const proofRating=ratedCases.length?ratedCases.reduce((sum,item)=>sum+(item.rating||0),0)/ratedCases.length:0;
  const estimatePct=proposal?.budget?Math.round(total/proposal.budget*100):0;
  const balance=Math.max(0,(proposal?.budget||0)-total);

  return <div className="pf-shell">
    <div className="pf-head"><div><div className="eyebrow">COMMERCIAL STUDIO</div><h1>Proposal Factory</h1><p>Turn a real client enquiry into a confident, evidence-backed proposal in minutes.</p></div><div className="pf-head-actions">{notice&&<span className="pf-saved">{notice}</span>}{mode==="document"&&<button className="btn" onClick={()=>window.print()}>Print / Save PDF</button>}<button className="btn primary" onClick={()=>{setBrief("");setProposal(null);setMode("brief");setTab("proposals")}}>New proposal</button></div></div>
    <div className="pf-tabs"><button className={tab==="proposals"?"on":""} onClick={()=>setTab("proposals")}>Proposals <b>{records.length}</b></button><button className={tab==="ratecard"?"on":""} onClick={()=>setTab("ratecard")}>Live rate card <b>{rateItems.length}</b></button><button className={tab==="proof"?"on":""} onClick={()=>setTab("proof")}>Proof library <b>{caseStudies.length}</b></button></div>

    {tab==="proposals"&&mode==="list"&&<div className="pf-list">{records.length===0?<div className="pf-empty"><span>01</span><h2>Your next pitch starts with the message already in your inbox.</h2><p>Paste an email, WhatsApp enquiry or meeting note. Proposal Factory extracts the opportunity, grounds pricing in your rate card and brings relevant past events into the story.</p><button className="btn primary" onClick={()=>setMode("brief")}>Create first proposal</button></div>:<div className="pf-proposal-grid">{records.map(r=><button className="pf-proposal-card" key={r.id} onClick={()=>{setProposal(r);setMode("document")}}><span className="pill confirmed">{r.status}</span><h3>{r.title}</h3><p>{r.company} · {r.city}</p><div><b>{money(r.budget)}</b><small>{new Date(r.createdAt).toLocaleDateString("en-IN")}</small></div></button>)}</div>}</div>}

    {tab==="proposals"&&mode==="brief"&&<div className="pf-brief-grid"><section><div className="eyebrow">01 · CLIENT SIGNAL</div><h2>Paste the brief exactly as it arrived.</h2><p>Messy is useful. Eventbot will identify the client, format, scale, budget, location and the decisions still missing.</p><textarea value={brief} onChange={e=>setBrief(e.target.value)} placeholder="Paste the email, WhatsApp message or meeting notes…"/><div className="pf-brief-actions"><button className="btn" onClick={()=>setBrief(sampleBrief)}>Load sample enquiry</button><span>{brief.length} characters</span><button className="btn primary" disabled={brief.trim().length<30||generating} onClick={generate}>{generating?"Building proposal…":"Build proposal →"}</button></div></section><aside><div className="eyebrow">WHAT EVENTBOT USES</div><div className="pf-source"><b>{caseStudies.length}</b><span>completed events<br/>as proof of delivery</span></div><div className="pf-source"><b>{rateItems.length}</b><span>live vendor rates<br/>for commercial grounding</span></div><div className="pf-source"><b>1</b><span>shared operating picture<br/>for leadership review</span></div></aside></div>}

    {tab==="proposals"&&mode==="document"&&proposal&&<div className="pf-workspace"><aside className="pf-doc-nav"><button onClick={()=>setMode("list")}>← All proposals</button><div className="eyebrow">DOCUMENT MAP</div>{["Cover","Executive case","Creative idea","Delivery plan","Proof","Commercials","Decision"].map((x,i)=><a href={`#pf-${i}`} key={x}><span>0{i+1}</span>{x}</a>)}<div className="pf-doc-total"><span>Working estimate</span><b>{money(total)}</b><small>{estimatePct}% of client budget · {money(balance)} headroom</small></div></aside><main className="pf-document">
      <section className="pf-sheet pf-cover" id="pf-0"><div className="pf-doc-brand">Event<em>bot</em> <span>PROPOSAL</span></div><div><span className="pf-kicker">Prepared for {proposal.company}</span><h2 contentEditable suppressContentEditableWarning onBlur={e=>patch("title",e.currentTarget.innerText)}>{proposal.title}</h2><p>{proposal.city} · {proposal.date} · {proposal.attendees.toLocaleString("en-IN")} guests</p></div><footer><span>Confidential</span><span>{new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"})}</span></footer></section>
      <section className="pf-sheet" id="pf-1"><div className="pf-kicker">EXECUTIVE CASE</div><h2>A proposal built around measurable confidence.</h2><p className="pf-big-edit" contentEditable suppressContentEditableWarning onBlur={e=>patch("objective",e.currentTarget.innerText)}>{proposal.objective}</p><div className="pf-facts pf-facts-4"><div><span>Format</span><b>{proposal.eventType}</b></div><div><span>Audience</span><b>{proposal.attendees.toLocaleString("en-IN")} guests</b></div><div><span>Budget ceiling</span><b>{money(proposal.budget)}</b></div><div><span>Current headroom</span><b>{money(balance)}</b></div></div><div className="pf-confidence"><div><span>Commercial coverage</span><b>{estimatePct}%</b><i><em style={{width:`${Math.min(100,estimatePct)}%`}}/></i><small>Working scope priced against the stated ceiling</small></div><div><span>Delivery confidence</span><b>High</b><i><em style={{width:"88%"}}/></i><small>Relevant proof, live rates and defined ownership</small></div></div></section>
      <section className="pf-sheet pf-concept" id="pf-2"><div className="pf-kicker">THE CREATIVE NORTH STAR</div><h2>One idea that holds the experience together.</h2><blockquote contentEditable suppressContentEditableWarning onBlur={e=>patch("concept",e.currentTarget.innerText)}>{proposal.concept}</blockquote><div className="pf-concept-line"><span>Energy</span><span>Recognition</span><span>Connection</span><span>Momentum</span></div></section>
      <section className="pf-sheet" id="pf-3"><div className="pf-kicker">DELIVERY ARCHITECTURE</div><h2>Clear ownership from approval to show day.</h2><div className="pf-timeline">{["Align","Design","Lock","Rehearse","Deliver"].map((label,i)=><div key={label}><span>0{i+1}</span><b>{label}</b><small>{["Objectives & success measures","Experience & production plan","Venue, talent & vendors","Content, cues & contingencies","Live command & reporting"][i]}</small></div>)}</div><div className="pf-scope">{proposal.scope.map((item,i)=><div key={i}><span>0{i+1}</span><p contentEditable suppressContentEditableWarning onBlur={e=>{const s=[...proposal.scope];s[i]=e.currentTarget.innerText;patch("scope",s)}}>{item}</p></div>)}</div><div className="pf-controls"><b>Built-in controls</b><span>Single accountable event lead</span><span>Budget change log</span><span>Vendor readiness checks</span><span>Show-day escalation matrix</span></div></section>
      <section className="pf-sheet" id="pf-4"><div className="pf-kicker">PROOF, NOT PROMISES</div><h2>Relevant delivery evidence.</h2><div className="pf-proof-metrics"><div><b>{selectedCases.length}</b><span>relevant events</span></div><div><b>{proofGuests.toLocaleString("en-IN")}</b><span>guests delivered</span></div><div><b>{money(proofValue)}</b><span>booked event value</span></div><div><b>{proofRating?proofRating.toFixed(1)+" / 5":"Verified"}</b><span>average reputation</span></div></div><div className="pf-proof-grid">{selectedCases.map(c=><article key={c.id}><span>{c.type.replaceAll("_"," ")} · {c.city}</span><h3>{c.name}</h3><p>{c.highlight}</p><footer><b>{c.attendees.toLocaleString("en-IN")} guests</b><b>{c.rating?`${c.rating.toFixed(1)} / 5`:money(c.valueInr)}</b></footer></article>)}</div></section>
      <section className="pf-sheet" id="pf-5"><div className="pf-kicker">WORKING COMMERCIALS</div><h2>Investment with visible headroom.</h2><div className="pf-investment"><div><span>Working estimate</span><b>{money(total)}</b><small>{estimatePct}% of budget ceiling</small></div><div><span>Unallocated headroom</span><b>{money(balance)}</b><small>Available for venue, upgrades or contingency</small></div><div className="pf-budget-ring" style={{background:`conic-gradient(#ba0013 0 ${Math.min(100,estimatePct)}%,#e2ddd4 ${Math.min(100,estimatePct)}% 100%)`}}><i><b>{estimatePct}%</b><span>allocated</span></i></div></div><div className="pf-allocation">{proposal.lines.slice(0,6).map((l,i)=>{const pct=total?Math.round(l.quantity*l.rate/total*100):0;return <div key={i}><span>{l.name}</span><i><em style={{width:`${pct}%`}}/></i><b>{pct}%</b></div>})}</div><table><thead><tr><th>Scope item</th><th>Qty</th><th>Unit</th><th>Rate</th><th>Total</th></tr></thead><tbody>{proposal.lines.map((l,i)=><tr key={i}><td contentEditable suppressContentEditableWarning onBlur={e=>{const lines=[...proposal.lines];lines[i]={...l,name:e.currentTarget.innerText};patch("lines",lines)}}>{l.name}</td><td>{l.quantity}</td><td>{l.unit}</td><td>{money(l.rate)}</td><td>{money(l.quantity*l.rate)}</td></tr>)}</tbody><tfoot><tr><td colSpan={4}>Working estimate</td><td>{money(total)}</td></tr></tfoot></table><p className="pf-note">Indicative and exclusive of applicable taxes. Final commercials follow venue, technical and supplier confirmation.</p></section>
      <section className="pf-sheet pf-next" id="pf-6"><div className="pf-kicker">DECISION & NEXT STEPS</div><h2>A low-friction path to a locked plan.</h2><p contentEditable suppressContentEditableWarning onBlur={e=>patch("nextSteps",e.currentTarget.innerText)}>{proposal.nextSteps}</p><div className="pf-decision-grid"><div><span>01</span><b>Approve direction</b><small>Confirm concept, outcomes and working ceiling.</small></div><div><span>02</span><b>Release discovery</b><small>Venue, technical and supplier validation begins.</small></div><div><span>03</span><b>Lock delivery</b><small>Contract, deposit, owners and master schedule.</small></div></div><div className="pf-assurance"><span>Estimate validity · 14 days</span><span>Change control · documented</span><span>Financial reporting · transparent</span></div><div className="pf-sign"><span>Prepared by Eventbot</span><b>Let’s build something worth remembering.</b></div></section>
    </main></div>}

    {tab==="ratecard"&&<div className="pf-data-view"><div><div className="eyebrow">COMMERCIAL SOURCE</div><h2>Live rate card</h2><p>Vendor offerings already in Eventbot become the commercial grounding for every proposal.</p></div><table><thead><tr><th>Item</th><th>Category</th><th>Partner</th><th>Unit</th><th>Rate</th></tr></thead><tbody>{rateItems.map(r=><tr key={r.id}><td><b>{r.name}</b></td><td>{String(r.category).replaceAll("_"," ")}</td><td>{r.vendor}</td><td>{r.unit}</td><td>{money(r.rateInr)}</td></tr>)}</tbody></table></div>}
    {tab==="proof"&&<div className="pf-data-view"><div><div className="eyebrow">CREDENTIALS ENGINE</div><h2>Past events become proof.</h2><p>Completed work is automatically available for proposal credentials—turning operational history into commercial advantage.</p></div><div className="pf-library-grid">{caseStudies.map(c=><article key={c.id}><span>{c.type.replaceAll("_"," ")} · {c.city}</span><h3>{c.name}</h3><p>{c.highlight}</p><div><b>{c.attendees.toLocaleString("en-IN")} guests</b><b>{c.rating?`${c.rating.toFixed(1)} / 5`:money(c.valueInr)}</b></div></article>)}</div></div>}
  </div>;
}
