\set ON_ERROR_STOP on

\copy (SELECT id AS client_id, name, company, contact_email, contact_phone, industry, lifetime_value_cents / 100.0 AS lifetime_value_inr, created_at FROM clients ORDER BY id) TO 'dashboard_mock_data/01_clients.csv' CSV HEADER

\copy (SELECT id AS venue_id, name, city, capacity, day_rate_cents / 100.0 AS day_rate_inr, contact, notes FROM venues ORDER BY id) TO 'dashboard_mock_data/02_venues.csv' CSV HEADER

\copy (SELECT e.id AS event_id, e.code AS event_code, e.name AS event_name, e.type AS event_type, e.status, c.company AS client, v.name AS venue, v.city, t.name AS lead_team, e.starts_on, e.ends_on, to_char(e.starts_at AT TIME ZONE 'Asia/Kolkata', 'YYYY-MM-DD HH24:MI') AS starts_at_ist, to_char(e.ends_at AT TIME ZONE 'Asia/Kolkata', 'YYYY-MM-DD HH24:MI') AS ends_at_ist, e.expected_attendees, e.confirmed_attendees, e.projected_revenue_cents / 100.0 AS projected_revenue_inr, e.booked_revenue_cents / 100.0 AS booked_revenue_inr, e.total_budget_cents / 100.0 AS total_budget_inr, e.spent_cents / 100.0 AS spent_inr, CASE WHEN e.total_budget_cents > 0 THEN round(e.spent_cents * 100.0 / e.total_budget_cents, 2) ELSE 0 END AS budget_used_pct, e.reputation_score, e.highlight FROM events e LEFT JOIN clients c ON c.id=e.client_id LEFT JOIN venues v ON v.id=e.venue_id LEFT JOIN teams t ON t.id=e.lead_team_id ORDER BY e.starts_on, e.name) TO 'dashboard_mock_data/03_events_calendar.csv' CSV HEADER

\copy (SELECT id AS vendor_id, name AS vendor_name, category, city, contact_name, contact_phone, rating, reliability_pct, preferred, notes FROM vendors ORDER BY category, preferred DESC, name) TO 'dashboard_mock_data/04_vendor_master.csv' CSV HEADER

\copy (SELECT o.id AS offering_id, o.vendor_id, v.name AS vendor_name, v.category, o.sku, o.unit, o.base_price_cents / 100.0 AS base_price_inr, o.peak_multiplier, round((o.base_price_cents / 100.0) * o.peak_multiplier, 2) AS peak_price_inr, o.min_order, o.lead_time_days FROM vendor_offerings o LEFT JOIN vendors v ON v.id=o.vendor_id ORDER BY v.category, v.name, o.sku) TO 'dashboard_mock_data/05_vendor_pricing.csv' CSV HEADER

\copy (SELECT * FROM (SELECT 'BOOK-' || ev.id AS booking_reference, e.code AS event_code, e.name AS event_name, e.type::text AS event_type, e.status::text AS event_status, e.starts_on, e.ends_on, to_char(e.starts_at AT TIME ZONE 'Asia/Kolkata', 'YYYY-MM-DD HH24:MI') AS starts_at_ist, to_char(e.ends_at AT TIME ZONE 'Asia/Kolkata', 'YYYY-MM-DD HH24:MI') AS ends_at_ist, ve.name AS venue, v.id AS vendor_id, v.name AS vendor_name, v.category::text AS category, v.contact_name, v.contact_phone, ev.offering_sku AS service_or_rfq, ev.quantity, ev.quoted_cents / 100.0 AS quoted_inr, ev.booked_cents / 100.0 AS booked_inr, ev.status AS booking_status FROM event_vendors ev LEFT JOIN events e ON e.id=ev.event_id LEFT JOIN vendors v ON v.id=ev.vendor_id LEFT JOIN venues ve ON ve.id=e.venue_id UNION ALL SELECT r.code || '-V' || v.id AS booking_reference, e.code, e.name, e.type::text, e.status::text, e.starts_on, e.ends_on, to_char(e.starts_at AT TIME ZONE 'Asia/Kolkata', 'YYYY-MM-DD HH24:MI'), to_char(e.ends_at AT TIME ZONE 'Asia/Kolkata', 'YYYY-MM-DD HH24:MI'), ve.name, v.id, v.name, v.category::text, v.contact_name, v.contact_phone, r.title, 1, q.quoted_cents / 100.0, CASE WHEN q.status='awarded' THEN q.quoted_cents / 100.0 ELSE NULL END, 'rfq_' || q.status::text FROM rfq_quotes q JOIN rfqs r ON r.id=q.rfq_id JOIN events e ON e.id=r.event_id JOIN vendors v ON v.id=q.vendor_id LEFT JOIN venues ve ON ve.id=e.venue_id) schedule ORDER BY starts_on, category, vendor_name) TO 'dashboard_mock_data/06_vendor_event_schedule.csv' CSV HEADER

\copy (SELECT b.id AS budget_line_id, e.code AS event_code, e.name AS event_name, e.type AS event_type, e.starts_on, b.category AS budget_category, b.planned_cents / 100.0 AS planned_inr, b.actual_cents / 100.0 AS actual_inr, (b.planned_cents-b.actual_cents) / 100.0 AS variance_inr, CASE WHEN b.planned_cents > 0 THEN round(b.actual_cents * 100.0 / b.planned_cents, 2) ELSE 0 END AS used_pct, b.notes FROM budget_lines b LEFT JOIN events e ON e.id=b.event_id ORDER BY e.starts_on, e.name, b.category) TO 'dashboard_mock_data/07_budget_lines.csv' CSV HEADER

\copy (SELECT e.code AS event_code, e.name AS event_name, e.type AS event_type, sum(b.planned_cents) / 100.0 AS planned_total_inr, sum(b.actual_cents) / 100.0 AS actual_total_inr, sum(b.planned_cents-b.actual_cents) / 100.0 AS variance_inr, CASE WHEN sum(b.planned_cents)>0 THEN round(sum(b.actual_cents)*100.0/sum(b.planned_cents),2) ELSE 0 END AS used_pct, e.projected_revenue_cents / 100.0 AS projected_revenue_inr, (e.projected_revenue_cents-sum(b.planned_cents)) / 100.0 AS projected_margin_inr FROM events e JOIN budget_lines b ON b.event_id=e.id GROUP BY e.id ORDER BY e.starts_on) TO 'dashboard_mock_data/08_budget_summary.csv' CSV HEADER

\copy (SELECT t.id AS team_id, t.name AS team_name, t.focus, t.lead_name, t.headcount, m.id AS member_id, m.name AS member_name, m.role, array_to_string(m.skill_tags, '; ') AS skills, m.utilization_pct, m.rating_avg FROM teams t LEFT JOIN team_members m ON m.team_id=t.id ORDER BY t.name, m.name) TO 'dashboard_mock_data/09_teams_members.csv' CSV HEADER

\copy (SELECT a.id AS assignment_id, e.code AS event_code, e.name AS event_name, e.starts_on, e.ends_on, t.name AS team_name, m.id AS member_id, m.name AS member_name, m.role AS primary_role, a.role AS event_role, m.utilization_pct FROM event_assignments a LEFT JOIN events e ON e.id=a.event_id LEFT JOIN team_members m ON m.id=a.member_id LEFT JOIN teams t ON t.id=m.team_id ORDER BY e.starts_on, e.name, m.name) TO 'dashboard_mock_data/10_event_team_assignments.csv' CSV HEADER

\copy (SELECT r.id AS rfq_id, r.code AS rfq_code, r.title, r.category, r.status, e.code AS event_code, e.name AS event_name, r.needed_by, r.budget_ceiling_cents / 100.0 AS budget_ceiling_inr, r.notes, r.created_by, r.created_at, r.sent_at, r.closes_at, av.name AS awarded_vendor FROM rfqs r LEFT JOIN events e ON e.id=r.event_id LEFT JOIN vendors av ON av.id=r.awarded_vendor_id ORDER BY r.created_at DESC) TO 'dashboard_mock_data/11_rfqs.csv' CSV HEADER

\copy (SELECT i.id AS rfq_item_id, r.code AS rfq_code, r.title AS rfq_title, i.sku, i.unit, i.quantity, i.specs FROM rfq_items i LEFT JOIN rfqs r ON r.id=i.rfq_id ORDER BY r.code, i.id) TO 'dashboard_mock_data/12_rfq_items.csv' CSV HEADER

\copy (SELECT q.id AS quote_id, r.code AS rfq_code, r.title AS rfq_title, r.category, r.budget_ceiling_cents / 100.0 AS budget_ceiling_inr, v.id AS vendor_id, v.name AS vendor_name, v.rating, v.reliability_pct, v.preferred, q.status AS quote_status, q.quoted_cents / 100.0 AS quoted_inr, (r.budget_ceiling_cents-q.quoted_cents) / 100.0 AS ceiling_headroom_inr, q.lead_time_days, q.validity_days, q.submitted_at, q.notes FROM rfq_quotes q LEFT JOIN rfqs r ON r.id=q.rfq_id LEFT JOIN vendors v ON v.id=q.vendor_id ORDER BY r.code, q.quoted_cents NULLS LAST) TO 'dashboard_mock_data/13_rfq_vendor_quotes.csv' CSV HEADER

\copy (SELECT rr.id AS recipient_id, r.code AS rfq_code, v.id AS vendor_id, v.name AS vendor_name, v.contact_name, v.contact_phone, rr.invited_at, rr.responded_at, CASE WHEN rr.responded_at IS NULL THEN 'pending' ELSE 'responded' END AS response_status FROM rfq_recipients rr LEFT JOIN rfqs r ON r.id=rr.rfq_id LEFT JOIN vendors v ON v.id=rr.vendor_id ORDER BY r.code, v.name) TO 'dashboard_mock_data/14_rfq_recipients.csv' CSV HEADER

\copy (SELECT rv.id AS review_id, e.code AS event_code, e.name AS event_name, e.type AS event_type, rv.source, rv.score, rv.nps, rv.quote, rv.author, rv.reviewed_on FROM event_reviews rv LEFT JOIN events e ON e.id=rv.event_id ORDER BY rv.reviewed_on DESC) TO 'dashboard_mock_data/15_reputation_reviews.csv' CSV HEADER

\copy (SELECT id AS market_id, name AS market_event, organizer, type AS event_type, city, starts_on, expected_attendees, est_ticket_price_cents / 100.0 AS estimated_ticket_price_inr, signal, notes FROM market_intel ORDER BY starts_on, name) TO 'dashboard_mock_data/16_market_intelligence.csv' CSV HEADER

\copy (SELECT tt.id AS tier_id, e.code AS event_code, e.name AS event_name, tt.tier_name, tt.price_cents / 100.0 AS ticket_price_inr, tt.inventory, tt.sold, (tt.inventory-tt.sold) AS remaining, (tt.sold*tt.price_cents) / 100.0 AS booked_ticket_revenue_inr FROM ticket_tiers tt LEFT JOIN events e ON e.id=tt.event_id ORDER BY e.starts_on, tt.price_cents) TO 'dashboard_mock_data/17_ticket_pricing.csv' CSV HEADER

\copy (SELECT s.id AS sponsor_id, e.code AS event_code, e.name AS event_name, s.name AS sponsor_name, s.tier, s.amount_cents / 100.0 AS amount_inr, s.status FROM sponsors s LEFT JOIN events e ON e.id=s.event_id ORDER BY e.starts_on, s.amount_cents DESC) TO 'dashboard_mock_data/18_sponsors.csv' CSV HEADER

\copy (SELECT e.code AS event_code, e.name AS wedding_name, e.status, c.company AS client, v.name AS venue, v.city, e.starts_on, e.ends_on, to_char(e.starts_at AT TIME ZONE 'Asia/Kolkata', 'YYYY-MM-DD HH24:MI') AS starts_at_ist, to_char(e.ends_at AT TIME ZONE 'Asia/Kolkata', 'YYYY-MM-DD HH24:MI') AS ends_at_ist, e.expected_attendees, e.confirmed_attendees, e.projected_revenue_cents / 100.0 AS projected_revenue_inr, e.total_budget_cents / 100.0 AS total_budget_inr, e.spent_cents / 100.0 AS spent_inr, e.highlight FROM events e LEFT JOIN clients c ON c.id=e.client_id LEFT JOIN venues v ON v.id=e.venue_id WHERE e.type='wedding' ORDER BY e.starts_on) TO 'dashboard_mock_data/19_wedding_events.csv' CSV HEADER
